export const FETCH_ALL_SCHEDULES = "FETCH_ALL_SCHEDULES";
export const FETCH_ALL_SCHEDULES_SUCCESS = "FETCH_ALL_SCHEDULES_SUCCESS";
export const FETCH_ALL_SCHEDULES_FAILED = "FETCH_ALL_SCHEDULES_FAILED";
export const FETCH_ALL_SCHEDULES_PENDING = "FETCH_ALL_SCHEDULES_PENDING";

export const FETCH_ONE_SCHEDULES = "FETCH_ONE_SCHEDULES";
export const FETCH_ONE_SCHEDULES_SUCCESS = "FETCH_ONE_SCHEDULES_SUCCESS";
export const FETCH_ONE_SCHEDULES_FAILED = "FETCH_ONE_SCHEDULES_FAILED";
export const FETCH_ONE_SCHEDULES_PENDING = "FETCH_ONE_SCHEDULES_PENDING";

export const ADD_SCHEDULES = "ADD_SCHEDULES";
export const ADD_SCHEDULES_SUCCESS = "ADD_SCHEDULES_SUCCESS";
export const ADD_SCHEDULES_FAILED = "ADD_SCHEDULES_FAILED";
export const ADD_SCHEDULES_PENDING = "ADD_SCHEDULES_PENDING";

export const REMOVE_SCHEDULES = "REMOVE_SCHEDULES";
export const REMOVE_SCHEDULES_SUCCESS = "REMOVE_SCHEDULES_SUCCESS";
export const REMOVE_SCHEDULES_FAILED = "REMOVE_SCHEDULES_FAILED";
export const REMOVE_SCHEDULES_PENDING = "REMOVE_SCHEDULES_PENDING";

export const BASE_URL = `http://localhost:8001/schedules/`;
