export const FETCH_ALL_SUPERVISORS = "FETCH_ALL_SUPERVISORS";
export const FETCH_ALL_SUPERVISORS_SUCCESS = "FETCH_ALL_SUPERVISORS_SUCCESS";
export const FETCH_ALL_SUPERVISORS_FAILED = "FETCH_ALL_SUPERVISORS_FAILED";
export const FETCH_ALL_SUPERVISORS_PENDING = "FETCH_ALL_SUPERVISORS_PENDING";

export const FETCH_ONE_SUPERVISORS = "FETCH_ONE_SUPERVISORS";
export const FETCH_ONE_SUPERVISORS_SUCCESS = "FETCH_ONE_SUPERVISORS_SUCCESS";
export const FETCH_ONE_SUPERVISORS_FAILED = "FETCH_ONE_SUPERVISORS_FAILED";
export const FETCH_ONE_SUPERVISORS_PENDING = "FETCH_ONE_SUPERVISORS_PENDING";

export const ADD_SUPERVISORS = "ADD_SUPERVISORS";
export const ADD_SUPERVISORS_SUCCESS = "ADD_SUPERVISORS_SUCCESS";
export const ADD_SUPERVISORS_FAILED = "ADD_SUPERVISORS_FAILED";
export const ADD_SUPERVISORS_PENDING = "ADD_SUPERVISORS_PENDING";

export const REMOVE_SUPERVISORS = "REMOVE_SUPERVISORS";
export const REMOVE_SUPERVISORS_SUCCESS = "REMOVE_SUPERVISORS_SUCCESS";
export const REMOVE_SUPERVISORS_FAILED = "REMOVE_SUPERVISORS_FAILED";
export const REMOVE_SUPERVISORS_PENDING = "REMOVE_SUPERVISORS_PENDING";

export const EDIT_SUPERVISOR_SUCCESS = "EDIT_SUPERVISOR_SUCCESS";
export const EDIT_SUPERVISOR_FAILED = "EDIT_SUPERVISOR_FAILED";
export const EDIT_SUPERVISOR_PENDING = "EDIT_SUPERVISOR_PENDING";

export const BASE_URL = `http://localhost:8001/supervisors/`;
