export const FETCH_ALL_OPERATORS = "FETCH_ALL_OPERATORS";
export const FETCH_ALL_OPERATORS_SUCCESS = "FETCH_ALL_OPERATORS_SUCCESS";
export const FETCH_ALL_OPERATORS_FAILED = "FETCH_ALL_OPERATORS_FAILED";
export const FETCH_ALL_OPERATORS_PENDING = "FETCH_ALL_OPERATORS_PENDING";

export const FETCH_ONE_OPERATORS = "FETCH_ONE_OPERATORS";
export const FETCH_ONE_OPERATORS_SUCCESS = "FETCH_ONE_OPERATORS_SUCCESS";
export const FETCH_ONE_OPERATORS_FAILED = "FETCH_ONE_OPERATORS_FAILED";
export const FETCH_ONE_OPERATORS_PENDING = "FETCH_ONE_OPERATORS_PENDING";

export const ADD_OPERATORS = "ADD_OPERATORS";
export const ADD_OPERATORS_SUCCESS = "ADD_OPERATORS_SUCCESS";
export const ADD_OPERATORS_FAILED = "ADD_OPERATORS_FAILED";
export const ADD_OPERATORS_PENDING = "ADD_OPERATORS_PENDING";

export const REMOVE_OPERATORS = "REMOVE_OPERATORS";
export const REMOVE_OPERATORS_SUCCESS = "REMOVE_OPERATORS_SUCCESS";
export const REMOVE_OPERATORS_FAILED = "REMOVE_OPERATORS_FAILED";
export const REMOVE_OPERATORS_PENDING = "REMOVE_OPERATORS_PENDING";

export const BASE_URL = `http://localhost:8001/operators/`;
